@startuml

title __TEXTSEARCHERBETA's Class Diagram__\n

  package  {
    package textStructure {
      class Block {
      }
    }
  }
  

  package  {
    package textStructure {
      class BlockResult {
      }
    }
  }
  

  package  {
    package textStructure {
      class Corpus {
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.dictionarySearch {
          class DictionaryIndexer {
          }
        }
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.suffixtree {
          class Edge {
          }
        }
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.suffixtree {
          class EdgeBag {
          }
        }
      }
    }
  }
  

  package  {
    package textStructure {
      class Entry {
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.suffixtree {
          class GeneralizedSuffixTree {
          }
        }
      }
    }
  }
  

  package  {
    package indexing {
      interface Iindexing {
      }
    }
  }
  

  package  {
    package indexing {
      class Indexer {
      }
    }
  }
  

  package  {
    package rules {
      interface IparsingRule {
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        interface IsearchAlgorithm {
        }
      }
    }
  }
  

  package  {
    package utils {
      class MD5 {
      }
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.suffixtree {
          class Node {
          }
        }
      }
    }
  }
  

  package  {
    package utils {
      class Stemmer {
      }
    }
  }
  

  package  {
    package utils {
      class Stopwords {
      }
    }
  }
  

  package  {
    class TextSearcher {
    }
  }
  

  package  {
    package indexing {
      package indexing.dataStructures {
        package indexing.dataStructures.suffixtree {
          class Utils {
          }
        }
      }
    }
  }
  

  package  {
    package textStructure {
      class WordResult {
      }
    }
  }
  

  Block o-- IparsingRule : parsingRule
  BlockResult -up-|> Block
  Corpus -up-|> Iterable
  DictionaryIndexer -up-|> IsearchAlgorithm
  Edge o-- Node : dest
  EdgeBag -up-|> Map
  Entry o-- IparsingRule : parseRule
  Entry o-- IsearchAlgorithm : index
  Entry o-- Corpus : origin
  GeneralizedSuffixTree o-- Node : root
  GeneralizedSuffixTree o-- Node : activeLeaf
  Indexer -up-|> Iindexing
  Indexer o-- IsearchAlgorithm : searchAlg
  Indexer o-- Corpus : origin
  Indexer o-- IparsingRule : parseRule
  Node o-- Node : suffix
  WordResult o-- Corpus : origin
  WordResult o-- Entry : sourceFile
  WordResult o-- Block : location


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
